[workspace]
members = ["bot", "esp"]

resolver = "3"

[workspace.dependencies]
rumqttc = "0.24.0"
config = "0.15.11"
serde = { version = "1", features = ["derive"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = "thin"
